server:
  port: 8080

spring:
  datasource:
    username: root
    password: Pru_Pru696
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch-size: 5
        order_inserts: true
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
    - url: http://playback.ru
      name: PlayBack.Ru
    - url: https://dombulgakova.ru
      name: Дом Булгакова
    - url: https://bolshoi.ru
      name: Большой Театр
    - url: https://www.rsl.ru
      name: Российская Государсвенная Библиотека
    - url: https://oteatre.info
      name: Журнал Театр

jsoup-settings:
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
  referrer: LearningSearchEngine