server:
  port: 8081

spring:
  datasource:
    username: root
    password: Pru_Pru696
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch-size: 5
        order_inserts: true
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
#    - url: https://lenta.ru
#      name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox
    - url: http://playback.ru
      name: PlayBack.Ru
    - url: https://dombulgakova.ru
      name: Дом Булгакова

jsoup-settings:
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
  referrer: LearningSearchEngine